### PR TITLE
Attributes v2

### PR DESCRIPTION
**Pull request by beberlei**
RFC: https://wiki.php.net/rfc/attributes_v2

### Required work

- [x] Full resolve class names, currently hardcoded NOFQ
- [x] `ReflectionAttribute::getAsObject` implementation.
- [x] Fix name inconsistencies, attribute_value should become attribute_argument, attribute_list should be the top definition of `<< attributes >>` in parser.
- [x] Memory leaks
- [x] Multiple arguments with a constant expression seem to be ignored by parser
- [x] Add support for attributes on `ReflectionParameter`
- [x] Implement $name filter for attribute or subclass of
- [x] Add `PhpAttribute` and ``PhpCompilerAttribute`` classes
- [x] Validate correctness of compiler attributes during compile step.

### Examples

- `Opcache\Jit` attribute: #7

### CODE REVIEW

**Comment by brzuchal** [comment]
@beberlei why forbidding the use of two attributes with the same name? While I cannot find a good example from Doctrine and Symfony Routing component, I can imagine `<<ParamConverter()>>` being used several times describing the conversion of params individually.

**Comment by tsantos84** [comment]
> @beberlei why forbidding the use of two attributes with the same name? While I cannot find a good example from Doctrine and Symfony Routing component, I can imagine `<<ParamConverter()>>` being used several times describing the conversion of params individually.

For class validation, we could use the same annotation twice on one attribute:

```php
class Foo {
    <<Length(groups=['bar'], min=10)>>
    <<Length(groups=['baz'], min=20)>>
    private string $foo;
}
```

**Comment by tsantos84** [comment]
Any special reason to not allow annotations for function arguments? It could be useful to annotate, for example, an argument to hold request content body like this:

```php
class MyController {
    function fooAction(<<RequestBody>> string $body) {}
    function barAction(<<RequestBody(required=false)>> string ?$body) {}
}
```

Dependency Injection tools can use argument annotations to improve its autowiring mechanism.

**Comment by beberlei** [comment]
@tsantos84 Yes and no, arguments don't have docblocks either, so the internal structure isn't as prepared for this. I will see what should be done about this.

**Comment by zmitic** [comment]
Question; I understand we can't have ``@`` for annotations **now** but if this is for PHP8, couldn't we get it? 
BC can be broken in major versions and STFU operator can be replaced with some other. 


But whatever happens, I really hope we could get them for arguments as well. It opens a whole new world of autowiring possibilities  :beer:

**Comment by mehranhadidi** [comment]
I agree with @zmitic. I really hope we can have this feature with `@`. It can be a lot nicer & convenient to read & write. Thank anyway

**Comment by stollr** [comment]
Just an idea: Maybe it would be better to use the namespace `Php\Lang\` for this kind of symbols?

**Comment by brzuchal** [comment]
Please stop talking about namespaces, this has nothing to do with that. Most of the internals opinion is about the right to use top-level namespace _(unprefixed)_ for all kind of things related to PHP core.

The naming of the interface to implement is also a minor thing. It doesn't make a difference if that's gonna be Attributes or Annotations, the biggest advantage here is getting it to be widely accepted as a feature itself - which is about a way to provide additional metadata in a structured way using resolvable class names and arguments for all places which are reflectable currently.

I believe either @beberlei nor anyone wanna discuss adding Attributes/Annotations for method/function parameters for now. I know that part is already reflectable but that might come over next time in a separate RFC. Just keep the focus on getting it done in the way it could be accepted.

**Comment by garygreen** [comment]
> the biggest advantage here is getting it to be widely accepted as a feature itself - which is about a way to provide additional metadata in a structured way using resolvable class names and arguments for all places which are reflectable currently.

We already have that, it's called docblocks.

Rather than introducing new syntax, would it make more sense to create a "docblock reflection API" for functions? Docblocks is a well documented and understood format for developers and flexible so it will allow consumers to do whatever they like with them.

**Comment by garygreen** [comment]
Another consideration - would the syntax of this proposal possibly affect generics? As someone mentioned on reddit:

> please make sure you arent making generic syntax impossible with this. My hopes are low for generics, but if we do get them and the syntax isnt &lt;T> I'm gonna have a mental breakdown.

😂

**Comment by Saphyel** [comment]
What about the option of depricating in PHP 7.5 the @ and use it for this in PHP 8?
Python, TypeScript, etc... use it in this way so I think is a great opportunity to remove a bad practice and use a standard from other languages.

**Comment by beberlei** [comment]
@Saphyel There will be no version 7.5 and `@` is not necessarily a bad practice, functions like fopen and file_get_contents sometimes have to set them.

**Comment by zmitic** [comment]
I don't mind <<>> syntax, I am sure PHPStorm will nicely display it. Minor concern about readability would be this:

```php
public function __construct(<<Inject(MyInterface::class)>> $tagged)
```

vs this:

```php
public function __construct(@Inject(MyInterface::class) $tagged)
```

but really, it is not a big deal; other languages have other characters and no one cares.



But I think @garygreen gave excellent idea. Even if we could get ``@`` character, doc blocks are still more useful. Example: if Reflection could read this:

```php
/**
 * This class does something with array of tagged services
 *
 * @param ServiceLocator<MyInterface> $tagged
 */
public function __construct($tagged)
```

we could not only autowire tagged services but also get static analysis in just one line of code. This would shut up all those people annoying about generics, including me :smile:

**Comment by tzsk** [comment]
This is a great addition to PHP. Can we also look at other options instead of `<<>>`. More like,

1. Double at: `@@Required`
2. At scope resolution `@::Required`
3. At tilde `@~Required`

And many more...

It would be great if we just use the opening `<<`

**Comment by m50** [comment]
I really love the idea of this, and I'm perfectly happy with the << >> notation as I personally think it would look better with full namespaces (`<<\App\Annotations\Something>>` rather than `@\App\Annotations\Something`, the @\ looks weirder).

But my one thing I think is missing, and maybe it fits better in a separate RFC as an addition to this one, but I think it's kind of lacking in the "Decorators" department.

I think there should probably be a couple extra interfaces (with actual functions to call):

1. `AssignableAttribute` => `public function assign(mixed $value): mixed;`
2. `InstantiableAttribute` => `public function instantiate(object $object): object;`
3. `CallableAttribute` => `public function call(callable $object, array $parameterList): callable;`

These would then have the function definitions required as above.

Then, anything with the `AssignableAttribute` has the `assign` function called when the object gets assigned to. Usually, this is a property of a class.

A class would usually be what has the `InstantiableAttribute`, and that gets called whenever `new` is called for that class.

And `CallableAttribute` is used whenever a callable is executed (I.e. an invokable class or a function or method).

Example of an `AssignableAttribute` (using your validation example):

```php
<?php

namespace App\Attributes\Validator;

use Php\Attribute;
use Php\AssignableAttribute;
use App\Attributes\Validator\Exceptions\ValidationException;

class Min implements Attribute, AssignableAttribute
{
    private int $minVal;
    public function __construct(int $minVal)
    {
        $this->minVal = $minVal;
    }
    public function assign($object)
    {
        if (is_numeric($object) && $object < $this->minVal) {
            throw new ValidationException();
        } elseif (is_string($object) && strlen($object) < $this->minVal) {
            throw new ValidationException();
        }

        return $object
    }
}
```

And how it's used:

```php
namespace App;

class Object
{
    <<Validator\Min(5)>>
    <<Validator\Max(250)>>
    public string $description;
}
```

Now, if we have:

```php
$object = new Object;

$object->description = 'hi!'; // Throws a ValidationException.

$object->description = 'helllllooooooo'; // Acceptable, gets assigned.
```

Additionally, this could modify it, for example, have a password property always be Bcrypted when assigned to.

I also have an example for an `InstantiableAttribute`:

```php
<?php

namespace App\Attributes;

use Php\Attribute;
use Php\InstantiableAttribute;

class Singleton implements Attribute, InstantiableAttribute
{
    private static array $instantiated = [];

    public function instantiate(object $object): object
    {
        $class = get_class($object);
        if (! isset(static::$instantiated[$class])) {
            static::$instantiated[$class] = $object;
        }

        return static::$instantiated[$class];
    }
}
```

And then it's used like so:

```php
<?php

namespace App;

use App\Attribute\Singleton;

<<Singleton>>
class MySuperObject
{
    // Do stuff...
}

$o = new MySuperObject;

$o2 = new MySuperObject; // Same object as $o because of the singleton attribute
```

Lastly, here is an example of a `CallableAttribute` (Though, this is a bit of a contrived example):

```php
<?php

namespace App\Attributes;

use Php\Attribute;
use Php\CallableAttribute;

class MutateTo implements Attribute, CallableAttribute
{
    private string $class;

    public function __construct(string $class)
    {
        $this->class = $class;
    }

    public function call(callable $object, array $parameterList): callable
    {
        return function () use ($object, $parameterList) {
            $returnVal = $object(...$parameterList);
            $class = $this->class;

            return new $class($returnVal);
        };
    }
}
```

And then it can be used as such:

```php

namespace App;

<<Attributes\MutateTo(AnotherObject::class)>>
class InvokableObject
{
    public function __invoke(string $param1)
    {
        // Do something

        return 2; // Whatever needs to be passed into the constructor of AnotherObject.
    }
}
```

As you can see, it's very clear how having Attributes be able to affect specific actions can be useful. And of course, one attribute *could* implement all of these, if it made sense to do so, and these can all be accessed using Reflection as well, but the key thing is, the language automatically runs these decorators at the appropriate time without having to use Reflection 100% of the time. This falls in line with decorators from other languages as well, which do not all require reflection for their implementation.

With the current implementation, it isn't possible to do a lot of things these decorators would offer, without a tertiary class (or the class using the decorators) implementing some reflection to handle, which has a bit of unnecessary separation (and potentially duplication of code). Additionally, currently, there isn't much purpose to the Attribute being a class, assigning from containing some data, as it doesn't actually do anything itself, so granting it the ability to implement functionality I feel would be very important.

**Comment by beberlei** [comment]
@m50 these are all great ideas in the scope of Aspect Oriented Programming.

They can be built on top of this Attributes feature with an extension or in core, this RFC focus is bringing the metadata into core first, and then we can see what we can built on top. Otherwise its going to be too large a step.

At least the singleton feature is something that frameworks could already build into their containers/factories with attributes:

```
<<Singleton>>
class MySuperObject
{
}

$object1 = Factory::get(MySuperObject::class);
$object2 = Factory::get(MySuperObject::class);
```

**Comment by beberlei** [comment]
@garygreen @zmitic A reflection docblock API would **not** be helpful, because it cannot be strict. There are alreay gazillions of docblocks out there, so an API parsing them must make sure it works with various different styles already out there. This will lead to a lenient parser, that means it cannot really verify if something is an attribute in a docblock, or if someone made a typo. As a result you get a class of bugs where neither IDEs nor PHP language can hint the developer that they made a typo, which is something that should be avoided.

In addition, a docblock reflection API requires a parser, which needs to be written in C. That means we need a new language inside a language and everything that follows. The maintenance overhead, vs making this explicit in the already existing language, with already existing statements / expressions support is significant.

**Comment by garygreen** [comment]
@beberlei 

> A reflection docblock API would not be helpful, because it cannot be strict. There are alreay gazillions of docblocks out there, so an API parsing them must make sure it works with various different styles already out there

There isn't a million styles out there, docblock is a [defined standard](https://docs.phpdoc.org/latest/guides/docblocks.html) and used widely by developers. If I may rephrase what you were alluding to is the ability to add different parameters types etc that can be "non-standard" - but the format itself in terms of syntax is standard at this point.

> This will lead to a lenient parser, that means it cannot really verify if something is an attribute in a docblock, or if someone made a typo

This is somewhat true, but it's worth noting this current PR implementation has similar problems in that you can make a typo too and it could have a different intended outcome during runtime to what's expected. In other words, nothing is validated and guaranteed to work. It's just meta data expressed in a different way.

Furthermore, PHP could introduce the concept of "strict docblocks" where if the format is not recognised as by the standard then it will fail to run.

```php
<?php

declare(strict_docblocks=1);

// Everything in this file must conform to the docblock standard as defined by php...
```

> In addition, a docblock reflection API requires a parser, which needs to be written in C. That means we need a new language inside a language and everything that follows. The maintenance overhead

This is a good point, it's probably the biggest burden of creating a docblock reflection API because as you say it would require a seperate parser - but imo this would benefit the community trumedeously *right now* and would require minimal re-writing of existing code to use the new api. In constrast, this PR introduces syntax changes and would require potentially re-doing a whole codebase with this new syntax in mind.

These are all just suggestions. I don't have any technical understanding about PHP in terms of C or how it's coded. I'm just speaking from the perspective of a developer who can see a overall greater impact having a docblock / comment meta data reflection api rather than introducing syntax-level changes to add meta data to functions when we have already had such a thing for years and deeply integrated into our codebases and IDEs; docblocks.

I'm all for this feature in terms of it's intended goal and appreciate all the work you have done on it, I'm just challenging whether this current implementation is the best way forwards 😀

**Comment by garygreen** [comment]
One other area of concern could be performance - the reflection API is known to be a bit slow. If apps started to refactor their current approach to this new syntax and rely on the reflection API would that have any performance impact for complex apps? Is the reflection API cached in any-way?

**Comment by m50** [comment]
So, I will speak for what you mentioned, @garygreen. First off, Reflection is no longer that slow in PHP. Reflection is used heavily in Symfony and Laravel already, and is usually used in any Dependency Injection containers. In modern PHP, reflection is actually quite performant, a lot more so than some other languages out there, and there would actually only be performance improvements over docblocks, as there is no need to do parsing as well of the doc blocks.

As for strict doc blocks, the entire point of this is to get code OUT of comment blocks. Additionally, having strict doc blocks would mean a new doc block parser would have to be written in C, and have a parser inside of a parser, and that is wanting to be avoided here.

**Comment by cebe** [comment]
> @garygreen There isn't a million styles out there, docblock is a [defined standard](https://docs.phpdoc.org/latest/guides/docblocks.html) and used widely by developers. If I may rephrase what you were alluding to is the ability to add different parameters types etc that can be "non-standard" - but the format itself in terms of syntax is standard at this point.

There is the documentation of PHPdoc but it is not really a specification or "defined standard". PHPdoc has a lot of flavors which differ in the way tags are written, the syntax and semantics of tags and their arguments. Different Tools and IDEs understand a different set of syntax and some of these are even conflicting. So if we'd want to parse PHPdoc  natively in PHP we'd first need to define a standard for it. An attempt to standardize PHPdoc is made in [PSR-5: PHPDoc](https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md) but as far as I remember it is far from finished and already quite complex.

> @m50 As for strict doc blocks, the entire point of this is to get code OUT of comment blocks. Additionally, having strict doc blocks would mean a new doc block parser would have to be written in C, and have a parser inside of a parser, and that is wanting to be avoided here.

:+1: there is a problem with annotations in comments, these are normally not considered part of the code. If the code relies on comments to be present for working properly, you run into problems  with [opcache.save-comments](https://www.php.net/manual/en/opcache.configuration.php#ini.opcache.save-comments). Having Attributes implemented outside of comments we avoid this problem.

> @garygreen One other area of concern could be performance - the reflection API is known to be a bit slow. If apps started to refactor their current approach to this new syntax and rely on the reflection API would that have any performance impact for complex apps?

First I'm not aware that Reflection is slow, but the argument about reflection does not fit here. you need reflection, for both ways, to get the docblock, but also to access Attributes. All current code that parses docblock annotations is using reflection to retrieve the docblock comment.

**Comment by tuqqu** [comment]
Can we discuss a bit more @zmitic 's initial proposal of replacing ~good~ old `@` operator with something else and using it for attributes/annotations?  Major version update can handle this kind of bc breaks.

**Comment by beberlei** [comment]
@tuqqu No they can't handle this kind of BC breaks. It will make the likelihood of this RFC passing 0.

**Comment by joelmedeiros** [comment]
@beberlei with this new paradigm, how to provide a solid solution to migrate our actual annotations to attributes?

**Comment by zmitic** [comment]
@beberlei Will it be possible now, or in future versions, to have something like this:

```
public function __construct(<<Tagged('form.type')>> iterable $formTypes)
```
or
```
public function __construct(<<Parameter('kernel.debug')>> bool $isDebug)
```

It would be very useful for autowiring.

**Comment by beberlei** [comment]
@joelmedeiros This is not something this RFC solves. The migration from docblocks to attributes is something that individual libraries need to plan and advise users on, probably in conjunction with usage of the rector or other automated refactoring libraries.

**Comment by beberlei** [comment]
@zmitic Yes, this could be added in the future. For now it would need to be done on the method level with `<<Parameter("isDebug", "kernel.debug")>>` for example

**Comment by beberlei** [comment]
@zmitic I just merged some changes from @kooldev into this PR that add support for attributes on parameters.

**Comment by zmitic** [comment]
>@zmitic I just merged some changes from @kooldev into this PR that add support for attributes on parameters.

That is **absolutely** amazing, thank you to both. Hopefully you will update RFC, I am sure lots of people would like to know about this change. Not using ``@`` will not be the main topic anymore :smile:

**Comment by javiereguiluz** [comment]
@beberlei thanks for working on this proposal. I guess you are tired of discussing about the syntax, but I'd like to add something about that.

The current proposal says that -->

```
Attributes may be applied to:

* functions (outside of classes)
* traits
* interfaces
* classes
* class methods
* class properties
* class constants
```

If we remove *"functions outside of classes"* from the list, could we use the `@...` syntax instead of `<< ... >>` ? Example:

```php
namespace App\Entity
{
    use Doctrine\ORM\Mapping as ORM;

    @ORM\Table("users")
    class SomeClass
    {
        @Uuid
        private const UUID;

        @ORM\Column(["unique" => true])
        public string $email;

        @Autowire(UserInterface::class)
        public function getSomething(UserInterface $user)
        {
            // ...
        }
    }
}
```

If I'm not missing something and this is true ... could we consider adding attributes/annotations without supporting them for "functions outside of classes"? Thanks!

**Comment by azjezz** [comment]
@javiereguiluz to answer your question, yes, but this means we remove functional programming from PHP. which would be the biggest BC break PHP has ever seen and I don't think anyone would agree on doing so.

> If I'm not missing something and this is true ... could we consider adding attributes/annotations without supporting them for "functions outside of classes"? Thanks!

No, the only way to support `@` is to remove functions from PHP, not dropping attributes support for them.

**Comment by garygreen** [comment]
Just thought I'd write up some pros/cons of this PR for those who are just casually browsing:

Advantages to this PR:

* **Easier introspection of meta data** - this is the primary purpose of this PR. It allows applications to use the reflection api to parse the meta data in an easier-way as compared to current Docblock approach where you need manually parse / use external tooling.
* **Stricter syntax, linting capabilties** - as compared to the way meta data is currently expressed in Docblocks - this PR has a defined syntax and scope so would allow PHP and IDEs to lint and potentially lesser area for bugs. Although Docblocks also have a syntax and scope, it's often more complex.
* **Possible future use cases** - for example deprecating functions by this meta data, hinting to PHP about OpCache code optimizations, etc.

Downsides to this PR:

* **Syntax** - the proposed syntax `<<Attribute>>` has been met with criticisms and suggestions of using `@param` - similar to how meta data is expressed in Docblocks at the moment.
* **Fatigue and confusion** - when should you use Attributes? When should you use docblocks instead? They are both meta data so are they interchangeable?
* **Wider implications and possible misuse in PHP community** - should we convert our entire codebase from Docblocks to Attributes? Potentially each framework will have their own `@param` equivalent which could cause fragmentation in the community and cause problems for IDEs. `<<SomeFramework\Param(...)>>`
* **Burden on IDEs, linters to implement new syntax** - currently Docblocks is the standard most IDEs use, some even with linting capabilities. Functionality wise, this PR doesn't add a huge array of benefits to IDEs or linters. Also poses the question how IDEs should highlight this, as meta data or actual code? An argument could be made for both.
* **Rewriting of codebases** - applications can already do everything in PR, albeit in a different syntax. It's just a new way of writing meta day in a way PHP can more easily introspect. Docblocks are the current standard in *every* codebase out there so that needs to be a consideration whether attributes provide enough benefits of rewriting large parts of codebases.
* **Feature parity status: largely unknown** - limited research has been conducted on the RFC with examples based on Doctrine and Symphony - whether the proposed syntax is enough to support and have mostly complete feature parity with how frameworks use such meta data isn't known at this point.

Possible alternatives to this PR:

* **Docblock introspection api** - rather than PHP simply providing a method to fetch the whole comment, instead provide a way to parse the docblock (in a simple way) which avoids the current problem with libraries having to write their own. 
* **Important docblock markers** - `opcache.save-comments` can potentially remove Dockblock comments which would cause applications that rely on that meta data to fail. A she-bang like marker could be added to docblocks to preserve such important meta data.

**Comment by j0hnys** [comment]
Although the `@` is unfortunately not available, how about `/@` ? It does not seem to have a problem and in a way is follows the convention the "/" followed by a character has special functionality (like `/**`, `//` ) . 

The `/**` is already used in order to encapsulate attributes now using symfony annotations, it seems that it blends more nicely.

**Comment by azjezz** [comment]
@j0hnys same issue.

https://3v4l.org/HUvch

I don't think there's a better alternative syntax than the one proposed. and I think we shouldn't block this RFC because of the proposed syntax.

**Comment by beberlei** [comment]
Just to reiterate, i am not going to change the proposed syntax with <<>>.

**Comment by kooldev** [comment]
Using `<<` and `>>` is basically the only syntax that works without introducing a new lexer token. It might seem tempting to use `@` and a `name` as rule for attributes, but this creates ambiguity in the grammar due to whitespace handling. Something like this:
```php
function (@Attr \stdClass $param) { }
```
The parser cannot decide if this is an attribute `@Attr\stdClass` or `@Attr` and a type-hint `stdClass`. Plus you get all the conflicts with the shutup operator. The only way to solve this is to introduce another lexer token (like `T_ATTRIBUTE` = `"@:""\\"?{LABEL}("\\"{LABEL})*` that does not permit whitespace. While I prefer this over the shifts-based syntax @beberlei suggested that a lot of core developers he talked to would not be willing to accept this...

**Comment by nunoperalta** [comment]
Guys,
What about using the following?

    @:foo("..")
    class Bar { }


It just doesn't feel right to have to type 4 characters (2 at the end), for every attribute. It would be great to find 2 chars that could work well just at the beginning, and look nice.

**Comment by kooldev** [comment]
@nunoperalta See my comment right before yours:
> like `T_ATTRIBUTE` = `"@:""\\"?{LABEL}("\\"{LABEL})*`

This is exactly what you suggested ;-). It is doable with very little effort and to me this is the only alternative syntax that is worth considering because it is more in line with what people are used to from Java and Python. You can have a look at kooldev/php-src#1 for an implementation. That being said I will however support this RFC because the feature is more important to me than the choice of syntax.

@beberlei I know that you want to stick with `<<` and `>>` but maybe it would be feasible to have a straw poll for that kind of thing to come to a decision that would finally stop this discussion. We could list the various advantages / disadvantages of both syntaxes and give a few examples in both dialects. Then have internals decide what they like best and stick with the result.

**Comment by cebe** [comment]
>  * **Fatigue and confusion** - when should you use Attributes? When should you use docblocks instead? They are both meta data so are they interchangeable?

[...]

>  * **Rewriting of codebases** - applications can already do everything in PR, albeit in a different syntax. It's just a new way of writing meta day in a way PHP can more easily introspect. Docblocks are the current standard in _every_ codebase out there so that needs to be a consideration whether attributes provide enough benefits of rewriting large parts of codebases.


There could be a very simple rule for this: if your meta data affects how the code is executed, it should be an Attribute, if it is documentation, use docblocks.
I don't see any benefit in replacing PHPDoc documentation with Attributes.

**Comment by moliata** [comment]
I do believe that `<<...>>` is the best syntax. As it increases compatibility with Hack language, does not interfere (with error control operator) or create any backwards-incompatible changes and also ensures that fewer bugs will be made (as there is less confusion).

Attributes goal is to provide an ability to add syntactic metadata. Its goal isn't to be aesthetically pleasing for everybody (as some people, e.g. me, do like the current syntax)

**Comment by azjezz** [comment]
@moliata Hack lang is actually switching to `@Foo()` syntax, this is being done after freeing up the `@` symbol.

**Comment by moliata** [comment]
> @moliata Hack lang is actually switching to `@Foo()` syntax, this is being done after freeing up the `@` symbol.

Could you give any official references to that, as I can't find any.

**Comment by azjezz** [comment]
@moliata nothing is official, the new syntax is still experimental, you can enable it by adding `allow_new_attribute_syntax = true` to your `.hhconfig` file.

you can see tests for it here: 
- https://github.com/facebook/hhvm/blob/fd8b548e3a4987d56babf93c14fcba842c95a6d4/hphp/test/slow/config-override/facts.php 
- https://github.com/facebook/hhvm/blob/16de749e8137ea5f1e213b38c8adf14257d8e544/hphp/hack/test/hackfmt/tests/atted_attribute/atted_attribute_specifications.php

:smile:

**Comment by moliata** [comment]
> @moliata nothing is official, the new syntax is still experimental, you can enable it by adding `allow_new_attribute_syntax = true` to your `.hhconfig` file.
> 
> you can see tests for it here: 
> - https://github.com/facebook/hhvm/blob/fd8b548e3a4987d56babf93c14fcba842c95a6d4/hphp/test/slow/config-override/facts.php 
> - https://github.com/facebook/hhvm/blob/16de749e8137ea5f1e213b38c8adf14257d8e544/hphp/hack/test/hackfmt/tests/atted_attribute/atted_attribute_specifications.php
> 
> :smile: 

Didn't know, thank you so much for informing!

**Comment by tuqqu** [comment]
@azjezz, thanks for sharing this, I think it's quite important for everyone to look at, because it means that we are trying to borrow the syntax from the only language which uses it and this language is trying to get rid of it.

**Comment by beberlei** [comment]
@tuqqu this is bot relevant. What is relevant is the fact that Hack used this WHILE they also needed to support @ for error supression. This is the situation we are facing with PHP, since nobody in core is seriously considering to remove it.

**Comment by javiereguiluz** [comment]
Note that we can use the `@...` syntax for annotations if we decide to not support them for stand-alone functions defined outside of classes.

In my experience, this is a reasonable constraint because annotations are used only when using classes (and traits, interfaces, etc.) and not when using stand-alone functions (e.g. in stand-alone PHP scripts). However, others might have a very different experience than me.

The fact that most programming languages use `@` ... and that one which was using `<< ... >>` is changing it to `@` could be a strong signal for us to reconsider this. Sorry for being so insisting and thanks for your patience 🙏

**Comment by beberlei** [comment]
@javiereguiluz 1. not supporting on functions is inconsistent, considering that these are the same things in the engine. 2. its not true that we can support it this way *without* making the parser context sensitive, which is the primary reason to avoid here, because that usually gets the Nay votes.

**Comment by beberlei** [comment]
@javiereguiluz also if you'd see the RFC, most programming languages actually use `[]` as syntax, ONLY java uses `@` if you consider that javascript and python have a decorator feature, not attributes/metadata per se.

**Comment by yaotzin1** [comment]
I am fine with <<Annotation>> syntax... also bracket syntax [Annotation] or maybe [@Annotation ]. Nevermind... please introduce it in PHP...

**Comment by moliata** [comment]
Edit: seems this is no longer a problem given that `Opcache\Jit` and `Opcache\NoJit` aren't part of this RFC.

**Comment by moliata** [comment]
@beberlei Is there any ETA when this RFC will move into a voting phase?

**Comment by beberlei** [comment]
@moliata depends on how much feedback the last changes get, probably in a few days to 2 weeks max.

**Comment by nunoperalta** [comment]
Not sure if this was already suggested,
but would it be possible that one of the questions in the poll is about which syntax is preferred by each voter? 

    <<Attr>>
    @:Attr


EDIT: I wonder why the downvotes... the syntax is what is causing the most controversy in this project, so I believe it would make sense to go for votes, not so?

EDIT 2: And the downvotes continued to arrive, even though beberlei has agreed with this suggestion, and those who downvoted me, upvoted beberlei when he agreed...

**Comment by azjezz** [comment]
@nunoperalta 
> I wonder why the downvotes... the syntax is what is causing the most controversy in this project, so I believe it would make sense to go for votes, not so?

No, its up to the PR author whether to vote on it or not. and @beberlei has already stated that the syntax won't be changed.

So the vote is clear: include this feature or not.

---

I really hope everyone stops suggestion alternative syntaxes, because I'm pretty sure the author already thought and tried other solutions, and came to the conclusion that this is the only possible syntax with no side effects/BC breaks.

If someone has a better solution, i'm pretty sure a new RFC can be opened after this one is approved to change the syntax.

Let's move on and get this amazing feature in PHP!

**Comment by nunoperalta** [comment]
@azjezz Thank you for the explanation. No problem with that, but I was just trying to be helpful and hopeful. This is the first time I was really involved on a PR for PHP, so I am not fully aware of the rules. The downvotes felt like I couldn't make a suggestion here.

> If someone has a better solution, i'm pretty sure a new RFC can be opened after this one is approved to change the syntax.

Well, the idea would be to avoid that, and then having two syntaxes appearing in repos/examples overtime, and then causing developers to be confused... but I understand.

Thanks again.

**Comment by beberlei** [comment]
At this point i plan to add a secondary vote to decide between <<>> and @: as symbols, since @kooldev helped me out on the code a lot and he wanted to try it. 

Personally I am going to keep advocsting for <<>> and voting this way, as well getting feedback from some voters they are leaning that way.

**Review by yaotzin1 — APPROVED** [review]

**Comment by beberlei** [comment]
Squashed commits and moved PR to master repo here: https://github.com/php/php-src/pull/5394

**Pull request closed without merging**
